apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
        - name: loki-storage
          persistentVolumeClaim:
            claimName: loki-pvc

      containers:
        - name: loki
          image: grafana/loki:3.5.5
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-minio-creds
                  key: access_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-minio-creds
                  key: secret_key

          args:
            - "-config.file=/etc/loki/conf/config.yaml"
            - "-config.expand-env=true"

          ports:
            - containerPort: 3100

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"

            limits:
              memory: "512Mi"
              cpu: "500m"

          volumeMounts:
            - name: loki-config
              mountPath: etc/loki/conf
            - name: loki-storage
              mountPath: /data

          readinessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 15
            periodSeconds: 10

        - name: memcached
          image: memcached:1.6.24-alpine
          args:
            # -m 64: Sets the memory limit to 64MB
            # -c 1024: Sets the max concurrent connections
            - "-m"
            - "256"
            - "-c"
            - "1024"

          resources:
            requests:
              memory: "256Mi"
              cpu: "0.05"

            limits:
              memory: "256Mi"
              cpu: "0.2"

          ports:
            - containerPort: 11211
