apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:3.5.5
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-minio-creds
                  key: access_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-minio-creds
                  key: secret_key

          args:
            - "-config.file=/etc/loki/conf/config.yaml"
            - "-config.expand-env=true"

          ports:
            - containerPort: 3100

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"

            limits:
              memory: "512Mi"
              cpu: "500m"

          volumeMounts:
            - name: loki-config
              mountPath: etc/loki/conf

          readinessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 15
            periodSeconds: 10

      volumes:
        - name: loki-config
          configMap:
            name: loki-config
