apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loki

resources:
  - namespace.yaml
  - external-secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - service-monitor.yaml
  

configMapGenerator:
- name: loki-config
  files:
  - config.yaml=conf/loki-config.yaml
  options:
    disableNameSuffixHash: true
