apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus

resources:
  - namespace.yaml
  - pvc.yaml
  - config.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  
