apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-ingress-route
spec:
  routes:
    - match: Host(`prometheus.prod.horna.local`)
      kind: Rule
      services:
        - name: prometheus-service
          port: 9090