apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
spec:
  privateKey:
    rotationPolicy: Always
  secretName: tls-secret
  commonName: replace.me.with.your.domain.com
  dnsNames:
    - replace.me.with.your.domain.com
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer 