apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      volumes:
        - name: grafana-config
          configMap:
            name: grafana-config

        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc

      containers:
        - name: grafana
          image: grafana/grafana:12.1.0
          args:
            - --config=/etc/grafana/conf/custom.ini
          ports:
            - name: http
              containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-config
              mountPath: /etc/grafana/conf
