apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana-metrics
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: grafana
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
