apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
- name: grafana-config
  files:
  - custom.ini=conf/prod-config.ini
  options:
    disableNameSuffixHash: true
  behavior: replace

patches:
  - path: patch-ingress.yaml
    target:
      kind: IngressRoute
      name: grafana-ingress-route
  - path: patch.cert.yaml
    target:
      kind: Certificate
      name: cert