apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
spec:
  privateKey:
    rotationPolicy: Always
  secretName: tls-secret
  commonName: grafana.prod.horna.local
  dnsNames:
    - grafana.prod.horna.local
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer 