apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200
      grpc_listen_port: 9095

    # Data ingestion receivers
    distributor:
      receivers:
        jaeger:
          protocols:
            grpc:
            thrift_compact:
            thrift_binary:
            thrift_http:
        zipkin:
        opencensus:
        otlp:
          protocols:
            grpc:
            http:

    compactor:
      compaction:
        block_retention: 336h # 14 days

    storage:
      trace:
        backend: s3
        s3:
          endpoint: minio-service.minio.svc.cluster.local:9000
          bucket: tempo-data
          insecure: true
          access_key: ${MINIO_ACCESS_KEY}
          secret_key: ${MINIO_SECRET_KEY}
        
        wal:
          path: /data/tempo/wal  

    cache:
      caches:
        - roles:
            - bloom
            - parquet-footer
            - parquet-page
            - frontend-search
        
          memcached:
            addresses: 127.0.0.1:11211

    metrics_generator:
      registry:
        external_labels:
          source: tempo
          cluster: docker-compose
      storage:
        path: /data/tempo/generator/wal
        remote_write:
          - url: http://mimir-service.mimir.svc.cluster.local:8080/api/v1/push
            send_exemplars: true
            headers:
              "X-Scope-OrgID": "cluster-internal"
      traces_storage:
        path: /data/tempo/generator/traces
