apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tempo

resources:
  - namespace.yaml
  - pvc.yaml
  - external-secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - service-monitor.yaml

configMapGenerator:
  - name: tempo-config
    files:
      - tempo.yaml=conf/tempo-config.yaml
    options:
      disableNameSuffixHash: true
