apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: tempo
  endpoints:
    - port: http-query
      path: /metrics
      interval: 15s
