apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alloy 

resources:
  - namespace.yaml 
  - rbac.yaml

helmCharts:
  - name: alloy
    repo: https://grafana.github.io/helm-charts
    version: "1.2.1" 
    releaseName: alloy
    namespace: alloy
    includeCRDs: true
    valuesInline:
      alloy:
        configMap:
          create: false 
          name: alloy-config 
        
        controller:
          type: daemonset
        extraEnv:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName

configMapGenerator:
- name: alloy-config
  files:
  - config.alloy=conf/alloy-config.alloy
  options:
    disableNameSuffixHash: true
