apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alloy-logs-events
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "events"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alloy-logs-events
roleRef:
  kind: ClusterRole
  name: alloy-logs-events
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: alloy
  namespace: alloy