apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system


configMapGenerator:
- name: coredns-custom
  files:
  - synology-dns.server=conf/synology-dns.server
  options:
    disableNameSuffixHash: true