apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: hcp-vault-dot-env-kv
spec:
  provider:
    vault:
      server: "http://10.0.10.11:8200"
      path: "dot_env_file"
      version: "v2"
      auth:
        appRole:
          path: "approle"
          roleId: "004769d9-d390-b54e-e49b-add30915bf4f"
          secretRef:
            name: vault-approle-secret
            key: secret-id
            namespace: external-secrets-operator
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: hcp-vault-infrastructure
spec:
  provider:
    vault:
      server: "http://10.0.10.11:8200"
      path: "infrastructure"
      version: "v2"
      auth:
        appRole:
          path: "approle"
          roleId: "004769d9-d390-b54e-e49b-add30915bf4f"
          secretRef:
            name: vault-approle-secret
            key: secret-id
            namespace: external-secrets-operator