apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mimir

resources:
  - namespace.yaml
  - external-secret.yaml
  - config.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  
