apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-secret
  namespace: minio
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: hcp-vault-infrastructure
    kind: ClusterSecretStore
  target:
    name: minio-secret
  data:
  - remoteRef:
      key: "minio.prod.horna.local"
      property: "root-password"
    secretKey: "MINIO_ROOT_PASSWORD"
  - remoteRef:
      key: "minio.prod.horna.local"
      property: "root-user"
    secretKey: "MINIO_ROOT_USER"