apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: alloy-config
    files:
      - config.alloy=conf/prod-config.alloy
    options:
      disableNameSuffixHash: true
    behavior: replace
